### ISSUE TITLE
C#上传文件失败

### ISSUE THREAD

**Issue by notmmao** [bmob/bmob-demo-csharp#2]
相关步骤:
1. 替换BmobBaseForm中APP_KEY.
2. 修改Program.cs,启动运行BmobFileUploadForm.
3. 选择文件后点击上传文件,出现异常.异常信息:"文件上传失败".

**Comment by winse** [comment]
全部更新下。已经修复了。

**Comment by beiguancyc** [comment]
下载最新，依然不能上传
